[book]
title = "Type Checking in Lean 4 日本語訳"
authors = ["Christopher A. Bailey", "contributions from the Lean community"]
language = "ja"
multilingual = false
src = "src"

[output.html]
git-repository-url = "https://github.com/lean-ja/type_checking_in_lean4_ja"
